Feature/button component
isdi-coders-2023/coding-adventure-Alexander-Guillen-front-202301-BCN pull request #1
Opened 2023-02-27 15:21 UTC by alexandergh132003

2023-02-27 16:07 UTC, catatarelli submitted a review, later dismissed

2023-02-27 16:23 UTC, alexandergh132003 commented on src/components/Button/Button.tsx
> +  innerText: string;
Cambiado

2023-02-27 16:23 UTC, alexandergh132003 commented on src/components/Button/Button.test.tsx
> +    test("Then it should show a button with accesible name 'Sign in'", () => {
Cambiado

2023-02-27 16:23 UTC, alexandergh132003 commented on src/components/Button/ButtonStyled.tsx
> +  background-color: #cccf18;
Variables hechas, sin Theme Provider.

2023-02-27 16:23 UTC, alexandergh132003 commented on src/GlobalStyles.tsx
> +button{
Cambiado.

2023-02-28 11:30 UTC, alexandergh132003 commented
@MMLORENA Hola, todos los cambios que me pidió la Cata ya están hechos.

2023-02-28 11:32 UTC, benjaminrae requested changes

2023-02-28 11:32 UTC, benjaminrae commented on src/theme/theme.tsx
> +export type Theme = typeof theme;
Asi no es como tipamos el theme, mira la documentacion

2023-02-28 11:32 UTC, benjaminrae commented on src/components/Button/ButtonStyled.tsx
> +  color: #1e1e1e;
Sacar este color a otro sitio

2023-02-28 11:50 UTC, alexandergh132003 commented on src/components/Button/ButtonStyled.tsx
> +  color: #1e1e1e;
Ok, ya está hecho.

2023-02-28 11:53 UTC, benjaminrae requested changes

2023-02-28 11:53 UTC, benjaminrae commented on src/components/Button/ButtonStyled.tsx
> +  font-family: "Saira Stencil One";
Este fuente esta en el Theme, porque no lo recoges de alli?

2023-02-28 11:55 UTC, alexandergh132003 commented on src/components/Button/ButtonStyled.tsx
> +  font-family: "Saira Stencil One";
Resuelto

2023-02-28 11:57 UTC, benjaminrae approved these changes
sigue con el formulario

2023-02-28 11:58 UTC, merged